version: '3.9'

services:
  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: cswni
      MONGO_INITDB_ROOT_PASSWORD: cswni
      MONGO_INITDB_DATABASE: ecommerce

    networks:
      - mongo_api

  
networks:
  mongo_api :
    driver: bridge
    